### ISSUE TITLE
Is there a mobile app for it?

### ISSUE THREAD

**Issue by JustGoscha** [lazerwalker/habit-squares#1]
Sorry to post it in issues, didn't know where else to post...

**Comment by lazerwalker** [comment]
There isn't a native mobile app for it, but it displays quite nicely in a web browser on an iPad (or presumably any other tablet). If you save it to the home screen as a favorite and launch it from there, it won't have any of Safari's UI chrome.

**Comment by lazerwalker** [comment]
(I'm sorry it took so long to reply — this issue somehow slipped my notice!)
